name: nlbs-cvae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - cudatoolkit=11.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pillow>=8.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scikit-image>=0.19.0
  - opencv>=4.5.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - tensorboard>=2.8.0
  - wandb>=0.13.0
  - lpips>=0.1.4
  - pytorch-fid>=0.2.1
  - albumentations>=1.3.0
  - einops>=0.6.0
  - xformers>=0.0.16
  - accelerate>=0.20.0
  - transformers>=4.25.0
  - datasets>=2.8.0
  - pip
  - pip:
    - opencv-python>=4.5.0
